const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
const FETCH_NEWS_VIEW = 'FETCH_NEWS_VIEW';
const FETCH_NEWS_START = 'FETCH_NEWS_START';
const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';

const ALERT_SUCCESS = 'ALERT_SUCCESS';
const ALERT_ERROR = 'ALERT_ERROR';
const ALERT_CLEAR = 'ALERT_CLEAR';

const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';

export default {
    FETCH_NEWS_ERROR,
    FETCH_NEWS_START,
    FETCH_NEWS_SUCCESS,
    FETCH_NEWS_VIEW,

    ALERT_SUCCESS,
    ALERT_ERROR,
    ALERT_CLEAR,

    LOGIN_START,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    LOGOUT
};
